project_id = "ypoqdlsiwpwzagolvhox"

[functions.extract-image-info]
verify_jwt = false

[functions.career-guidance]
verify_jwt = false

[functions.student-chatbot]
verify_jwt = false

[functions.cleanup-idle-accounts]
verify_jwt = false
