
-- Clean up test data
DELETE FROM subject_combinations WHERE name = 'kudzi';
DELETE FROM subjects WHERE name = 'kudzi';

-- ADD MISSING O-LEVEL SUBJECTS
INSERT INTO subjects (name, level, category, code, description) VALUES
  ('Combined Science', 'O-Level', 'Sciences', '5129', 'Combined physics, chemistry, and biology'),
  ('Integrated Science', 'O-Level', 'Sciences', '5006', 'Integrated approach to science disciplines'),
  ('Food and Nutrition', 'O-Level', 'Technical & Vocational', '5085', 'Study of food preparation, nutrition and health'),
  ('Fashion and Fabrics', 'O-Level', 'Technical & Vocational', '5086', 'Design and creation of garments and textiles'),
  ('Woodwork', 'O-Level', 'Technical & Vocational', '5115', 'Woodworking techniques and furniture construction'),
  ('Metalwork', 'O-Level', 'Technical & Vocational', '5116', 'Metalworking skills and fabrication'),
  ('Technical Graphics', 'O-Level', 'Technical & Vocational', '5117', 'Technical drawing and graphical communication'),
  ('Building Studies', 'O-Level', 'Technical & Vocational', '5118', 'Construction principles and building technology'),
  ('Textile Technology and Design', 'O-Level', 'Technical & Vocational', '5119', 'Textile production and design'),
  ('Statistics', 'O-Level', 'Sciences', '5384', 'Data collection, analysis and probability'),
  ('Shona', 'O-Level', 'Arts & Humanities', '3159', 'Shona language and literature'),
  ('Business Enterprise Skills', 'O-Level', 'Commercials', '5379', 'Entrepreneurship and business basics'),
  ('Home Management', 'O-Level', 'Technical & Vocational', '5064', 'Household management and family living'),
  ('Sport and Mass Displays', 'O-Level', 'Technical & Vocational', '5055', 'Physical activities and mass displays'),
  ('Principles of Accounts', 'O-Level', 'Commercials', '7101', 'Basic accounting principles'),
  ('Bible Knowledge', 'O-Level', 'Arts & Humanities', '2015', 'Study of biblical texts and themes')
ON CONFLICT DO NOTHING;

-- ADD MISSING A-LEVEL SUBJECTS
INSERT INTO subjects (name, level, category, code, description) VALUES
  ('Management of Business', 'A-Level', 'Commercials', '9198', 'Business management principles and practice'),
  ('Agriculture', 'A-Level', 'Agriculture', '9159', 'Agricultural science and farm management'),
  ('Ndebele', 'A-Level', 'Arts & Humanities', '9166', 'Ndebele language and literature'),
  ('Sport and Physical Education', 'A-Level', 'Technical & Vocational', '9055', 'Sport science and physical education'),
  ('Food Science', 'A-Level', 'Technical & Vocational', '9085', 'Food science and technology'),
  ('Textile Technology and Design', 'A-Level', 'Technical & Vocational', '9086', 'Advanced textile production and design'),
  ('Applied Mathematics', 'A-Level', 'Sciences', '9795', 'Applied mathematical methods'),
  ('Theatre Arts', 'A-Level', 'Arts & Humanities', '9270', 'Dramatic arts and theatre performance'),
  ('Media Studies', 'A-Level', 'Arts & Humanities', '9274', 'Mass media and communication studies'),
  ('Communication Skills', 'A-Level', 'Arts & Humanities', '9101', 'Advanced communication and language skills'),
  ('Pure Mathematics', 'A-Level', 'Sciences', '9164', 'Pure mathematical theory and proofs'),
  ('Religious Studies', 'A-Level', 'Arts & Humanities', '9014', 'Advanced religious and ethical studies'),
  ('Physical Education', 'A-Level', 'Technical & Vocational', '9396', 'Physical education theory and practice')
ON CONFLICT DO NOTHING;

-- ADD A-LEVEL COMBINATIONS
INSERT INTO subject_combinations (name, level, description, subjects, career_paths, is_active) VALUES
  ('Pre-Medical Sciences', 'A-Level', 'Biology, Chemistry, and Physics - ideal for medical school entry',
   '["Biology", "Chemistry", "Physics"]'::jsonb,
   ARRAY['Medical Doctor', 'Dentist', 'Pharmacist', 'Veterinarian', 'Physiotherapist'], true),
  ('Mathematical Sciences', 'A-Level', 'Mathematics, Further Mathematics, and Physics',
   '["Mathematics", "Further Mathematics", "Physics"]'::jsonb,
   ARRAY['Actuary', 'Statistician', 'Data Scientist', 'Research Scientist', 'Engineer'], true),
  ('Technical Sciences', 'A-Level', 'Mathematics, Physics, and Computer Science',
   '["Mathematics", "Physics", "Computer Science"]'::jsonb,
   ARRAY['Software Developer', 'Electrical Engineer', 'Network Administrator', 'Cybersecurity Analyst'], true),
  ('Agricultural Sciences', 'A-Level', 'Biology, Chemistry, and Agriculture',
   '["Biology", "Chemistry", "Agriculture"]'::jsonb,
   ARRAY['Agricultural Officer', 'Agricultural Economist', 'Veterinarian', 'Environmental Scientist'], true),
  ('Social Sciences', 'A-Level', 'Sociology, Psychology, and Economics',
   '["Sociology", "Psychology", "Economics"]'::jsonb,
   ARRAY['Social Worker', 'Psychologist', 'Human Resources Manager', 'Policy Analyst'], true),
  ('Humanities', 'A-Level', 'Geography, History, and Divinity/Religious Studies',
   '["Geography", "History", "Divinity"]'::jsonb,
   ARRAY['Teacher', 'Journalist', 'Diplomat', 'Tourism Manager', 'Archivist'], true),
  ('Pure Arts', 'A-Level', 'Literature in English, History, and Shona/Ndebele',
   '["Literature in English", "History", "Shona"]'::jsonb,
   ARRAY['University Lecturer', 'Journalist', 'Librarian', 'Writer', 'Teacher'], true),
  ('Law Pathway', 'A-Level', 'History, English Language, and Sociology/Divinity',
   '["History", "English Language", "Sociology"]'::jsonb,
   ARRAY['Lawyer', 'Magistrate', 'Legal Secretary', 'Diplomat', 'Policy Analyst'], true),
  ('Business Arts', 'A-Level', 'Accounting, Economics, and Geography',
   '["Accounting", "Economics", "Geography"]'::jsonb,
   ARRAY['Accountant', 'Financial Analyst', 'Estate Agent', 'Bank Manager', 'Economist'], true),
  ('Science-Commercial', 'A-Level', 'Mathematics, Accounting, and Economics',
   '["Mathematics", "Accounting", "Economics"]'::jsonb,
   ARRAY['Actuary', 'Accountant', 'Financial Analyst', 'Economist', 'Bank Manager'], true),
  ('Media and Communication', 'A-Level', 'English Language, Sociology, and Media Studies',
   '["English Language", "Sociology", "Media Studies"]'::jsonb,
   ARRAY['Journalist', 'Public Relations Officer', 'Film Producer', 'Graphic Designer'], true),
  ('Computer Science and Maths', 'A-Level', 'Computer Science, Mathematics, and Physics',
   '["Computer Science", "Mathematics", "Physics"]'::jsonb,
   ARRAY['Software Developer', 'Data Scientist', 'Cybersecurity Analyst', 'IT Support Specialist'], true),
  ('Accounting and Management', 'A-Level', 'Accounting, Management of Business, and Economics',
   '["Accounting", "Management of Business", "Economics"]'::jsonb,
   ARRAY['Accountant', 'Auditor', 'Tax Consultant', 'Marketing Manager', 'Human Resources Manager'], true),
  ('Geography and Sciences', 'A-Level', 'Geography, Biology, and Chemistry',
   '["Geography", "Biology", "Chemistry"]'::jsonb,
   ARRAY['Environmental Scientist', 'Geologist', 'Meteorologist', 'Town Planner', 'Surveyor'], true),
  ('Food and Nutrition Sciences', 'A-Level', 'Food Science, Biology, and Chemistry',
   '["Food Science", "Biology", "Chemistry"]'::jsonb,
   ARRAY['Food Scientist', 'Dietitian', 'Nutritionist', 'Quality Assurance Manager'], true),
  ('Art and Design Pathway', 'A-Level', 'Art and Design, English Language, and History',
   '["Art and Design", "English Language", "History"]'::jsonb,
   ARRAY['Graphic Designer', 'Interior Designer', 'Fashion Designer', 'Architect', 'Photographer'], true)
ON CONFLICT DO NOTHING;

-- ADD MISSING CAREERS
INSERT INTO careers (name, field, description, salary_range, job_outlook, skills_required, is_active) VALUES
  ('Social Worker', 'Social Services', 'Provides support and guidance to individuals and families', '$300-$800/month', 'Growing', ARRAY['Empathy', 'Communication', 'Problem-solving', 'Counselling'], true),
  ('Psychologist', 'Healthcare', 'Studies human behaviour and provides mental health support', '$500-$1500/month', 'Growing', ARRAY['Analytical thinking', 'Empathy', 'Research', 'Communication'], true),
  ('Actuary', 'Business & Finance', 'Analyses financial risk using mathematics and statistics', '$800-$3000/month', 'High demand', ARRAY['Mathematics', 'Statistics', 'Financial modelling', 'Risk assessment'], true),
  ('Auditor', 'Business & Finance', 'Examines financial records and ensures compliance', '$500-$2000/month', 'Stable', ARRAY['Accounting', 'Attention to detail', 'Analytical skills', 'Integrity'], true),
  ('Tax Consultant', 'Business & Finance', 'Advises on tax obligations and financial planning', '$500-$2000/month', 'Stable', ARRAY['Tax law', 'Accounting', 'Communication', 'Analytical skills'], true),
  ('Insurance Agent', 'Business & Finance', 'Sells and manages insurance policies', '$300-$1200/month', 'Stable', ARRAY['Sales', 'Communication', 'Risk assessment', 'Customer service'], true),
  ('Estate Agent', 'Business & Finance', 'Manages property sales, rentals and valuations', '$400-$1500/month', 'Growing', ARRAY['Negotiation', 'Marketing', 'Property law', 'Communication'], true),
  ('Economist', 'Business & Finance', 'Analyses economic trends and advises on policy', '$600-$2500/month', 'Stable', ARRAY['Economics', 'Statistics', 'Research', 'Analytical thinking'], true),
  ('Geologist', 'Science & Research', 'Studies earth materials, processes and history', '$500-$2000/month', 'Stable', ARRAY['Geology', 'Field research', 'Data analysis', 'GIS'], true),
  ('Surveyor', 'Construction', 'Measures and maps land for construction and planning', '$400-$1500/month', 'Stable', ARRAY['Mathematics', 'Surveying', 'GIS', 'Attention to detail'], true),
  ('Meteorologist', 'Science & Research', 'Studies weather patterns and climate', '$400-$1200/month', 'Stable', ARRAY['Physics', 'Mathematics', 'Data analysis', 'Computer skills'], true),
  ('Statistician', 'Science & Research', 'Applies statistical methods to collect and analyse data', '$500-$2000/month', 'High demand', ARRAY['Statistics', 'Mathematics', 'Data analysis', 'Programming'], true),
  ('Town Planner', 'Construction', 'Plans and designs urban and rural land use', '$500-$1500/month', 'Growing', ARRAY['Urban planning', 'GIS', 'Communication', 'Problem-solving'], true),
  ('Diplomat', 'Government', 'Represents Zimbabwe in international affairs', '$800-$3000/month', 'Competitive', ARRAY['International relations', 'Communication', 'Languages', 'Negotiation'], true),
  ('Policy Analyst', 'Government', 'Researches and advises on public policy', '$500-$1500/month', 'Stable', ARRAY['Research', 'Critical thinking', 'Writing', 'Economics'], true),
  ('Tourism Manager', 'Hospitality', 'Manages tourism operations and marketing', '$400-$1500/month', 'Growing', ARRAY['Tourism', 'Marketing', 'Management', 'Communication'], true),
  ('Hotel Manager', 'Hospitality', 'Manages hotel operations and guest services', '$400-$1500/month', 'Growing', ARRAY['Hospitality management', 'Leadership', 'Customer service', 'Finance'], true),
  ('Chef', 'Hospitality', 'Prepares meals and manages kitchen operations', '$300-$1200/month', 'Growing', ARRAY['Culinary arts', 'Creativity', 'Time management', 'Food safety'], true),
  ('Food Scientist', 'Science & Research', 'Studies food composition and develops food products', '$500-$1500/month', 'Growing', ARRAY['Food science', 'Chemistry', 'Quality control', 'Research'], true),
  ('Dietitian', 'Healthcare', 'Advises on nutrition and dietary requirements', '$400-$1200/month', 'Growing', ARRAY['Nutrition', 'Biology', 'Communication', 'Health sciences'], true),
  ('Optometrist', 'Healthcare', 'Examines eyes and prescribes corrective lenses', '$500-$2000/month', 'Stable', ARRAY['Optics', 'Biology', 'Patient care', 'Attention to detail'], true),
  ('Radiographer', 'Healthcare', 'Operates imaging equipment for medical diagnosis', '$400-$1200/month', 'Growing', ARRAY['Radiography', 'Physics', 'Patient care', 'Technology'], true),
  ('Medical Laboratory Scientist', 'Healthcare', 'Conducts laboratory tests for medical diagnosis', '$400-$1200/month', 'Stable', ARRAY['Laboratory techniques', 'Biology', 'Chemistry', 'Attention to detail'], true),
  ('Midwife', 'Healthcare', 'Provides care during pregnancy and childbirth', '$350-$1000/month', 'High demand', ARRAY['Nursing', 'Patient care', 'Communication', 'Emergency response'], true),
  ('Occupational Therapist', 'Healthcare', 'Helps patients recover daily living skills', '$400-$1200/month', 'Growing', ARRAY['Rehabilitation', 'Empathy', 'Problem-solving', 'Anatomy'], true),
  ('Librarian', 'Education', 'Manages library resources and information services', '$300-$800/month', 'Stable', ARRAY['Information management', 'Research', 'Organisation', 'IT skills'], true),
  ('Fashion Designer', 'Media & Communication', 'Designs clothing and fashion accessories', '$300-$1500/month', 'Growing', ARRAY['Design', 'Creativity', 'Sewing', 'Trend awareness'], true),
  ('Interior Designer', 'Construction', 'Designs functional and aesthetic interior spaces', '$400-$1500/month', 'Growing', ARRAY['Design', 'Creativity', 'Space planning', 'CAD'], true),
  ('Photographer', 'Media & Communication', 'Captures images for various purposes', '$200-$1200/month', 'Growing', ARRAY['Photography', 'Editing', 'Creativity', 'Lighting'], true),
  ('Film Producer', 'Media & Communication', 'Produces films and video content', '$300-$2000/month', 'Growing', ARRAY['Video production', 'Storytelling', 'Management', 'Editing'], true),
  ('Pilot', 'Transport', 'Operates aircraft for commercial or private flights', '$1000-$5000/month', 'Competitive', ARRAY['Aviation', 'Physics', 'Mathematics', 'Decision-making'], true),
  ('Telecommunications Engineer', 'Engineering', 'Designs and maintains communication systems', '$500-$2000/month', 'Growing', ARRAY['Telecommunications', 'Electronics', 'Networking', 'Problem-solving'], true),
  ('Biomedical Engineer', 'Engineering', 'Designs medical equipment and devices', '$500-$2000/month', 'Growing', ARRAY['Engineering', 'Biology', 'Medical devices', 'Problem-solving'], true),
  ('Industrial Engineer', 'Engineering', 'Optimises complex processes and systems', '$500-$2000/month', 'Stable', ARRAY['Engineering', 'Mathematics', 'Process optimisation', 'Analytics'], true),
  ('Agricultural Engineer', 'Engineering', 'Designs agricultural equipment and systems', '$400-$1500/month', 'Stable', ARRAY['Engineering', 'Agriculture', 'Design', 'Problem-solving'], true),
  ('Primary School Teacher', 'Education', 'Teaches primary school students across subjects', '$250-$600/month', 'High demand', ARRAY['Teaching', 'Patience', 'Communication', 'Creativity'], true),
  ('Banker', 'Business & Finance', 'Provides banking services and financial advice', '$400-$1500/month', 'Stable', ARRAY['Finance', 'Customer service', 'Numeracy', 'Communication'], true),
  ('Entrepreneur', 'Business & Finance', 'Starts and manages own business ventures', '$0-$10000/month', 'Growing', ARRAY['Business planning', 'Leadership', 'Risk-taking', 'Innovation'], true),
  ('Customs Officer', 'Government', 'Controls imports and exports at borders', '$400-$1000/month', 'Stable', ARRAY['Law', 'Attention to detail', 'Integrity', 'Communication'], true),
  ('Police Officer', 'Government', 'Maintains law and order in communities', '$300-$800/month', 'Stable', ARRAY['Law enforcement', 'Physical fitness', 'Communication', 'Integrity'], true)
ON CONFLICT DO NOTHING;
