
INSERT INTO diplomas (name, level, field, institution, description, is_active) VALUES
-- Higher National Diplomas (HND)
('HND in Accounting', 'Higher National Diploma', 'Commerce', 'Polytechnics/Technical Colleges', 'Advanced accounting qualification', true),
('HND in Business Management', 'Higher National Diploma', 'Commerce', 'Polytechnics/Technical Colleges', 'Advanced business management qualification', true),
('HND in Marketing', 'Higher National Diploma', 'Commerce', 'Polytechnics/Technical Colleges', 'Advanced marketing qualification', true),
('HND in Civil Engineering', 'Higher National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'Advanced civil engineering qualification', true),
('HND in Electrical Engineering', 'Higher National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'Advanced electrical engineering qualification', true),
('HND in Mechanical Engineering', 'Higher National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'Advanced mechanical engineering qualification', true),
('HND in Computer Science', 'Higher National Diploma', 'Technology', 'Polytechnics/Technical Colleges', 'Advanced computing qualification', true),
('HND in Electronics', 'Higher National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'Advanced electronics qualification', true),
('HND in Automotive Engineering', 'Higher National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'Advanced automotive engineering qualification', true),
('HND in Chemical Technology', 'Higher National Diploma', 'Science', 'Polytechnics/Technical Colleges', 'Advanced chemical technology qualification', true),
('HND in Mass Communication', 'Higher National Diploma', 'Media', 'Polytechnics/Technical Colleges', 'Advanced mass communication qualification', true),
('HND in Tourism and Hospitality', 'Higher National Diploma', 'Tourism', 'Polytechnics/Technical Colleges', 'Advanced tourism and hospitality qualification', true),
('HND in Agriculture', 'Higher National Diploma', 'Agriculture', 'Polytechnics/Technical Colleges', 'Advanced agriculture qualification', true),
('HND in Information Technology', 'Higher National Diploma', 'Technology', 'Polytechnics/Technical Colleges', 'Advanced IT qualification', true),
('HND in Human Resources Management', 'Higher National Diploma', 'Commerce', 'Polytechnics/Technical Colleges', 'Advanced HR management qualification', true),

-- National Diplomas
('National Diploma in Accounting', 'National Diploma', 'Commerce', 'Polytechnics/Technical Colleges', 'National diploma in accounting', true),
('National Diploma in Business Management', 'National Diploma', 'Commerce', 'Polytechnics/Technical Colleges', 'National diploma in business management', true),
('National Diploma in Marketing', 'National Diploma', 'Commerce', 'Polytechnics/Technical Colleges', 'National diploma in marketing', true),
('National Diploma in Civil Engineering', 'National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'National diploma in civil engineering', true),
('National Diploma in Electrical Engineering', 'National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'National diploma in electrical engineering', true),
('National Diploma in Mechanical Engineering', 'National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'National diploma in mechanical engineering', true),
('National Diploma in Computer Science', 'National Diploma', 'Technology', 'Polytechnics/Technical Colleges', 'National diploma in computer science', true),
('National Diploma in Electronics', 'National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'National diploma in electronics', true),
('National Diploma in Automotive Engineering', 'National Diploma', 'Engineering', 'Polytechnics/Technical Colleges', 'National diploma in automotive engineering', true),
('National Diploma in Chemical Technology', 'National Diploma', 'Science', 'Polytechnics/Technical Colleges', 'National diploma in chemical technology', true),
('National Diploma in Mass Communication', 'National Diploma', 'Media', 'Polytechnics/Technical Colleges', 'National diploma in mass communication', true),
('National Diploma in Tourism and Hospitality', 'National Diploma', 'Tourism', 'Polytechnics/Technical Colleges', 'National diploma in tourism and hospitality', true),
('National Diploma in Agriculture', 'National Diploma', 'Agriculture', 'Polytechnics/Technical Colleges', 'National diploma in agriculture', true),
('National Diploma in Information Technology', 'National Diploma', 'Technology', 'Polytechnics/Technical Colleges', 'National diploma in IT', true),
('National Diploma in Human Resources Management', 'National Diploma', 'Commerce', 'Polytechnics/Technical Colleges', 'National diploma in HR management', true),
('National Diploma in Secretarial Studies', 'National Diploma', 'Commerce', 'Polytechnics/Technical Colleges', 'National diploma in secretarial studies', true),
('National Diploma in Journalism', 'National Diploma', 'Media', 'Polytechnics/Technical Colleges', 'National diploma in journalism', true),

-- National Certificates
('National Certificate in Accounting', 'National Certificate', 'Commerce', 'Polytechnics/Technical Colleges', 'National certificate in accounting', true),
('National Certificate in Business Studies', 'National Certificate', 'Commerce', 'Polytechnics/Technical Colleges', 'National certificate in business studies', true),
('National Certificate in Marketing', 'National Certificate', 'Commerce', 'Polytechnics/Technical Colleges', 'National certificate in marketing', true),
('National Certificate in Civil Engineering', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in civil engineering', true),
('National Certificate in Electrical Engineering', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in electrical engineering', true),
('National Certificate in Mechanical Engineering', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in mechanical engineering', true),
('National Certificate in Computer Studies', 'National Certificate', 'Technology', 'Polytechnics/Technical Colleges', 'National certificate in computer studies', true),
('National Certificate in Electronics', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in electronics', true),
('National Certificate in Automotive Engineering', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in automotive engineering', true),
('National Certificate in Agriculture', 'National Certificate', 'Agriculture', 'Polytechnics/Technical Colleges', 'National certificate in agriculture', true),
('National Certificate in Secretarial Studies', 'National Certificate', 'Commerce', 'Polytechnics/Technical Colleges', 'National certificate in secretarial studies', true),
('National Certificate in Woodwork Technology', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in woodwork technology', true),
('National Certificate in Metalwork Technology', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in metalwork technology', true),
('National Certificate in Motor Mechanics', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in motor mechanics', true),
('National Certificate in Plumbing', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in plumbing', true),
('National Certificate in Bricklaying', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in bricklaying', true),
('National Certificate in Welding and Fabrication', 'National Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'National certificate in welding and fabrication', true),
('National Certificate in Hairdressing and Beauty', 'National Certificate', 'Vocational', 'Polytechnics/Technical Colleges', 'National certificate in hairdressing and beauty', true),
('National Certificate in Catering and Hospitality', 'National Certificate', 'Tourism', 'Polytechnics/Technical Colleges', 'National certificate in catering and hospitality', true),

-- Certificates
('Certificate in Nursing Aide', 'Certificate', 'Health', 'Health Training Institutions', 'Basic nursing aide certificate', true),
('Certificate in Primary Health Care', 'Certificate', 'Health', 'Health Training Institutions', 'Primary health care certificate', true),
('Certificate in Community Health', 'Certificate', 'Health', 'Health Training Institutions', 'Community health worker certificate', true),
('Certificate in Information Technology', 'Certificate', 'Technology', 'Polytechnics/Technical Colleges', 'Basic IT certificate', true),
('Certificate in Computer Studies', 'Certificate', 'Technology', 'Polytechnics/Technical Colleges', 'Basic computer studies certificate', true),
('Certificate in Business Studies', 'Certificate', 'Commerce', 'Polytechnics/Technical Colleges', 'Basic business studies certificate', true),
('Certificate in Bookkeeping', 'Certificate', 'Commerce', 'Polytechnics/Technical Colleges', 'Basic bookkeeping certificate', true),
('Certificate in Secretarial Studies', 'Certificate', 'Commerce', 'Polytechnics/Technical Colleges', 'Basic secretarial studies certificate', true),
('Certificate in Agriculture', 'Certificate', 'Agriculture', 'Agricultural Colleges', 'Basic agriculture certificate', true),
('Certificate in Animal Health', 'Certificate', 'Agriculture', 'Agricultural Colleges', 'Animal health certificate', true),
('Certificate in Horticulture', 'Certificate', 'Agriculture', 'Agricultural Colleges', 'Horticulture certificate', true),
('Certificate in Early Childhood Development', 'Certificate', 'Education', 'Teachers Colleges', 'ECD certificate', true),
('Certificate in Teaching', 'Certificate', 'Education', 'Teachers Colleges', 'Basic teaching certificate', true),
('Certificate in Social Work', 'Certificate', 'Social Sciences', 'Universities', 'Basic social work certificate', true),
('Certificate in Journalism', 'Certificate', 'Media', 'Polytechnics/Technical Colleges', 'Basic journalism certificate', true),
('Certificate in Fashion and Design', 'Certificate', 'Vocational', 'Polytechnics/Technical Colleges', 'Fashion and design certificate', true),
('Certificate in Catering', 'Certificate', 'Tourism', 'Polytechnics/Technical Colleges', 'Basic catering certificate', true),
('Certificate in Motor Mechanics', 'Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'Basic motor mechanics certificate', true),
('Certificate in Welding', 'Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'Basic welding certificate', true),
('Certificate in Carpentry and Joinery', 'Certificate', 'Engineering', 'Polytechnics/Technical Colleges', 'Basic carpentry certificate', true);
